spring.application.name=newsbook-backend
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Database Configuration
spring.datasource.url=jdbc:h2:file:./data/newsbook;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE;LOCK_TIMEOUT=10000
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server Configuration
server.port=8080
server.servlet.context-path=/api

# Logging
logging.level.root=INFO
logging.level.com.newsbook=DEBUG

# Ensure Spring Boot serves static resources from the /static directory
spring.web.resources.static-locations=classpath:/static/